services:
  - type: web
    name: gpt-bcra-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
